from __future__ import annotations

from typing import Dict, List, Literal, Optional, Union

from pydantic import BaseModel, Field, field_validator


class Citation(BaseModel):
    title: str
    authors_first: str
    year: int = 0
    journal_or_server: str
    doi: Optional[str] = None
    url: Optional[str] = None


class StudyDesign(BaseModel):
    design: Literal[
        "parallel_rct",
        "crossover_rct",
        "nonrandomized",
        "observational",
        "systematic_review",
        "meta_analysis",
        "other",
        "unknown",
    ] = "unknown"
    blinding: Literal["double_blind", "single_blind", "open_label", "unknown"] = "unknown"
    control_type: Literal["placebo", "usual_care", "diet_control", "active_control", "none", "unknown"] = (
        "unknown"
    )
    setting: Literal["single_center", "multi_center", "unknown"] = "unknown"
    duration_weeks: int = 0
    followup_weeks: int = 0
    washout_weeks: int = 0


class Population(BaseModel):
    mci_only: bool = True
    mci_definition: Optional[str] = None
    subtype: Literal["amnestic", "non_amnestic", "mixed", "unknown"] = "unknown"
    n_total: int = 0
    n_intervention: int = 0
    n_control: int = 0
    age_mean: float = 0.0
    age_sd: float = 0.0
    sex_female_percent: float = 0.0
    apoe4_reported: bool = False
    apoe4_percent: float = 0.0
    comorbidity_notes: Optional[str] = None
    baseline_cognition_measure: Optional[str] = None


class Intervention(BaseModel):
    category: Literal[
        "mct",
        "c8_caprylic",
        "c10_capric",
        "mct_mix",
        "ketone_salt",
        "ketone_ester",
        "ketogenic_diet",
        "other",
        "unknown",
    ] = "unknown"
    product_name: Optional[str] = None
    dose_value: float = 0.0
    dose_unit: Literal["g_per_day", "ml_per_day", "mg_per_day", "unknown"] = "unknown"
    dose_schedule: Optional[str] = None
    duration_weeks: int = 0
    route: Literal["oral", "other", "unknown"] = "unknown"
    cointerventions: List[str] = Field(default_factory=list)


class Comparator(BaseModel):
    description: Optional[str] = None
    dose_value: float = 0.0
    dose_unit: Literal["g_per_day", "ml_per_day", "mg_per_day", "unknown"] = "unknown"


class KetoneConfirmation(BaseModel):
    measured: bool = False
    metric: Literal["bHB", "acetoacetate", "ketones_unspecified", "unknown"] = "unknown"
    timepoints: List[str] = Field(default_factory=list)
    result_summary: Optional[str] = None


class Outcome(BaseModel):
    name: str
    timepoint_weeks: int = 0
    effect_direction: Literal["improved", "worsened", "no_change", "mixed", "unknown"] = "unknown"
    effect_size_type: Literal["mean_change", "between_group_diff", "percent_change", "p_value_only", "unknown"] = (
        "unknown"
    )
    value: float = 0.0
    sd: float = 0.0
    p_value: Optional[str] = None
    notes: Optional[str] = None


class Outcomes(BaseModel):
    cognition: List[Outcome] = Field(default_factory=list)
    adl_function: List[Outcome] = Field(default_factory=list)
    biomarkers: List[Outcome] = Field(default_factory=list)


class SafetyAdherence(BaseModel):
    adherence_reported: bool = False
    adherence_summary: Optional[str] = None
    adverse_events_reported: bool = False
    adverse_events_summary: Optional[str] = None
    dropout_n_total: int = 0
    dropout_reasons: List[str] = Field(default_factory=list)


class RiskOfBiasHints(BaseModel):
    randomization_clear: bool = False
    allocation_concealment_clear: bool = False
    blinding_clear: bool = False
    attrition_low: bool = False
    selective_reporting_suspected: bool = False
    notes: Optional[str] = None


class EligibilityFlags(BaseModel):
    include_for_mci_mct_review: bool = True
    reason_if_excluded: Optional[str] = None
    separate_analysis_tag: Literal[
        "primary_mct",
        "ketone_ester_or_salt",
        "ketogenic_diet",
        "mixed_population",
        "unknown",
    ] = "unknown"


class ExtractionQuality(BaseModel):
    confidence: Literal["high", "medium", "low"] = "low"
    missing_fields: List[str] = Field(default_factory=list)


class PaperTagging(BaseModel):
    """General Hybrid Tagging for all papers."""

    hard_tags: Dict[str, Union[str, int, float, None]] = Field(
        description="Exact values extracted from text (e.g. sample_size, species)"
    )
    soft_tags: List[str] = Field(
        description="Contextual tags generated by AI (e.g. #autophagy, #prevention)"
    )
    evidence_span: Optional[str] = Field(
        None,
        description="The exact sentence or fragment from text that justifies the tags.",
    )
    confidence: float = Field(0.0, description="Model's confidence score (0.0 to 1.0).")
    reasoning: Optional[str] = None


class TrialExtraction(BaseModel):
    paper_id: str
    citation: Citation
    study_design: StudyDesign = Field(default_factory=StudyDesign)
    population: Population = Field(default_factory=Population)
    intervention: Intervention = Field(default_factory=Intervention)
    comparator: Comparator = Field(default_factory=Comparator)
    ketone_confirmation: KetoneConfirmation = Field(default_factory=KetoneConfirmation)
    outcomes: Outcomes = Field(default_factory=Outcomes)
    safety_adherence: SafetyAdherence = Field(default_factory=SafetyAdherence)
    risk_of_bias_hints: RiskOfBiasHints = Field(default_factory=RiskOfBiasHints)
    eligibility_flags: EligibilityFlags = Field(default_factory=EligibilityFlags)
    extraction_quality: ExtractionQuality = Field(default_factory=ExtractionQuality)

    @field_validator("eligibility_flags")
    def check_mci_consistency(cls, value, values):
        """
        mci_only가 False이면 include_for_mci_mct_review도 False여야 함.
        데이터에 접근하기 위해 values.data를 사용합니다.
        """
        if "population" in values.data and not values.data["population"].mci_only:
            value.include_for_mci_mct_review = False
            if not value.reason_if_excluded:
                value.reason_if_excluded = "Population not MCI-only."
        return value

    def to_summary_block(self) -> str:
        """Obsidian 노트에 추가할 자동 요약 블록을 생성합니다."""
        from src.schemas.trial_summary import build_trial_summary_block

        return build_trial_summary_block(self)


__all__ = [
    "Citation",
    "StudyDesign",
    "Population",
    "Intervention",
    "Comparator",
    "KetoneConfirmation",
    "Outcome",
    "Outcomes",
    "SafetyAdherence",
    "RiskOfBiasHints",
    "EligibilityFlags",
    "ExtractionQuality",
    "PaperTagging",
    "TrialExtraction",
]
